### ISSUE TITLE
error on run

### ISSUE THREAD

**Issue by cbrherms** [mr-bjerre/hassio-remote-backup#8]
Currently getting the following error when runnings:

```
starting version 3.2.4
Adding SSH key
Creating local backup: "Automated backup 2018-05-01 23:26"
ERROR
panic: interface conversion: interface is nil, not string
goroutine 1 [running]:
panic(0x2c5f60, 0x107d01c0)
	/home/travis/.gimme/versions/go1.7.6.linux.amd64/src/runtime/panic.go:500 +0x33c
github.com/home-assistant/hassio-cli/command/helpers.DisplayOutput(0x107e4000, 0x24, 0x200, 0x1070a900)
	/home/travis/gopath/src/github.com/home-assistant/hassio-cli/command/helpers/common.go:118 +0x3c8
github.com/home-assistant/hassio-cli/command/helpers.ExecCommand(0x2f4bff, 0x9, 0x2f4560, 0x8, 0x0, 0x0, 0x10784300, 0x1070a930, 0x26, 0x0, ...)
	/home/travis/gopath/src/github.com/home-assistant/hassio-cli/command/helpers/common.go:155 +0x308
github.com/home-assistant/hassio-cli/command.CmdSnapshots(0x10778420)
	/home/travis/gopath/src/github.com/home-assistant/hassio-cli/command/snapshots.go:62 +0x3a4
github.com/urfave/cli.HandleAction(0x2ae6d8, 0x323760, 0x10778420, 0x0, 0x0)
	/home/travis/gopath/src/github.com/urfave/cli/app.go:503 +0xf0
github.com/urfave/cli.Command.Run(0x2f4bff, 0x9, 0x0, 0x0, 0x409d30, 0x1, 0x1, 0x2ff148, 0x28, 0x0, ...)
	/home/travis/gopath/src/github.com/urfave/cli/command.go:165 +0x6b8
github.com/urfave/cli.(*App).Run(0x107648c0, 0x1070a0f0, 0x5, 0x6, 0x0, 0x0)
	/home/travis/gopath/src/github.com/urfave/cli/app.go:259 +0x8b0
main.main()
	/home/travis/gopath/src/github.com/home-assistant/hassio-cli/main.go:22 +0x108
Backup created: 
Copying .tar to /mnt/DATA/Backups/HASSIO/AutoBackup on 192.168.0.12 using SCP
Warning: Permanently added '192.168.0.12' (ECDSA) to the list of known hosts.
.tar: No such file or directory
```

Checked that i can successfully passwordless login with the supplied keys and all seems correct.

any thoughts?
Running Homeassistant 0.68

**Comment by cbrherms** [comment]
Scratch that, this was due to a snapshot-create call having already been made in the background.
Stops the addon from shutting itself down though
